####
# Blazing fast run config that's also used by Taskcluster CI
###

experiment:
  name: ci
  src: ru
  trg: en

  teacher-ensemble: 1

  archive-corpora: false

  mono-max-sentences-src:
    total: 1000
    per-dataset: 500
  mono-max-sentences-trg:
    total: 1000
    per-dataset: 500
  spm-sample-size: 1000
  spm-vocab-size: 1000
  spm-vocab-split: false

  best-model: chrf

  opuscleaner-mode: "custom"
  teacher-mode: "two-stage"
  teacher-decoder: marian
  corpus-max-sentences: 1000
  student-model: "tiny"

  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_ada83_v1: 0.0
      opus_ELRC-3075-wikipedia_health_v1: 0.6

  monocleaner:
    mono-src:
      default-threshold: 0.5
      dataset-thresholds:
        news-crawl_news_2008: 0.0
        opus_tldr-pages_v2023-08-29: 0.7
    mono-trg:
      default-threshold: 0.9
      dataset-thresholds:
        opus_tldr-pages_v2023-08-29: 0.6

  hplt-min-doc-score:
    mono-src: 7.0
    mono-trg: 9.0

marian-args:
  training-backward:
    # Run training for 10 updates, and display 5 updates. Only validate and save the
    # model once.
    disp-freq: "2"
    save-freq: "25"
    valid-freq: "50"
    after: 50u
    dim-vocabs: "1000 1000"
  training-teacher:
    disp-freq: "1"
    save-freq: "25"
    valid-freq: "50"
    after: 50u
    dim-vocabs: "1000 1000"
    task: transformer-base
  training-student:
    disp-freq: "1"
    save-freq: "25"
    valid-freq: "50"
    after: 50u
    dim-vocabs: "1000 1000"
  training-student-finetuned:
    disp-freq: "1"
    save-freq: "25"
    valid-freq: "50"
    after: 50u
    dim-vocabs: 1000 1000
  decoding-backward:
    mini-batch-words: "2000"
  decoding-teacher:
    mini-batch-words: "1000"
    precision: float16

# Ensure that we have adequate coverage for dataset types in CI.
datasets:
  train:
    - opus_ada83/v1
    - opus_ELRC-3075-wikipedia_health/v1
    - url_https://storage.googleapis.com/releng-translations-dev/data/en-ru/pytest-dataset.[LANG].zst
    - mtdata_Tilde-airbaltic-1-eng-rus
  devtest:
    - flores_dev
    - sacrebleu_aug-upper_wmt19
  test:
    - flores_devtest
  mono-src:
    - news-crawl_news.2008
    - opus_tldr-pages/v2023-08-29 # 36 sentences
  mono-trg:
    - news-crawl_news.2007
    - opus_tldr-pages/v2023-08-29 # 39,646 sentences

continuation: {}

# Publishes to the "ci" project.
wandb-publication: true
target-stage: all-pipeline
taskcluster:
  split-chunks: 2
  upload-bucket: development
  worker-classes:
    default: gcp-spot
